export default [
    {
        id: "1",
        pic: "/assets/c16f12e0-city-5571-169fd60e503.jpg",
        country: "Sierra Leone",
        city: "Freetown",
        timeframe: "December March 2023",
        description: "Freetown, the capital city of Sierra Leone, is a vibrant and culturally diverse coastal metropolis nestled along the shimmering waters of the Atlantic Ocean. Known for its rich history, Freetown was founded by freed African-American and Afro-Caribbean slaves in the late 18th century, making it a unique and historically significant destination. Visitors to Freetown can explore its bustling markets, historic landmarks, and beautiful beaches while immersing themselves in the warm and welcoming atmosphere of this West African gem.",
        google: "https://earth.google.com/web/search/Sierra+Leone/@8.42228365,-11.8374897,78.76680897a,589125.14198115d,35y,0h,0t,0r/data=CnYaTBJGCiQweGYwMTA2MTgzYWFiZjM0MzoweDUzNjllOWNkYzcyY2Y3MTkZwARu3c3rIEAhMQVrnE2PJ8AqDFNpZXJyYSBMZW9uZRgCIAEiJgokCSLMh1BPUDVAESDMh1BPUDXAGVvoZKEur0ZAIdPRi9I2-0zA",
    },
    {
        id: "2",
        pic: "/assets/ce115d52-5bd1-4f78-8a2a-6f1ec518d239.jpg",
        country: "The Bahamas",
        city: "Nassau",
        timeframe: "December 2022",
        description: "Nassau, the capital of the Bahamas, is a picturesque tropical paradise situated on the island of New Providence. It is renowned for its stunning white-sand beaches, crystal-clear turquoise waters, and vibrant Bahamian culture. Visitors to Nassau can enjoy a blend of relaxation and adventure, with opportunities for water sports, exploring historic sites like Fort Charlotte, and indulging in delicious local cuisine.",
        google: "https://earth.google.com/web/search/bahamas/@24.45480796,-76.01569911,5.84677265a,1083085.81686786d,35y,0h,0t,0r/data=CnIaSBJCCiUweDg4ZDY5YTNiYjI0ODBmM2Q6MHgxMzNlYjQ4MzZhYzc3OWU1GSno9pLGCDlAIcQDyqZcWVPAKgdiYWhhbWFzGAIgASImCiQJkjxqD8wgOUARuSbA8MvvOEAZaU3w0XNMU8AhfckTzqdnU8A",
    },
    {
        id: "3",
        pic: "/assets/GettyImages-1234024326-1.webp",
        country: "Cuba",
        city: "Havana",
        timeframe: "May 2021",
        description: "Havana, the capital city of Cuba, is a captivating blend of history, culture, and vibrant energy. Its streets are adorned with colorful colonial architecture, vintage cars, and lively music echoing through the air. Visitors to Havana can immerse themselves in its rich heritage, from exploring the historic Old Havana district to savoring the flavors of Cuban cuisine and dancing to the infectious rhythms of salsa music.",
        google: "https://earth.google.com/web/search/cuba/@24.42067483,-75.98370911,2.789691a,1083868.94272702d,35y,0h,0t,0r/data=Cm8aRRI_CiUweDg4Y2Q0OTA3MGY3YTRjYjU6MHg3OThjZjc1MjkxMTBhNDFhGYV1492RhTVAIblt36P-cVPAKgRjdWJhGAIgASImCiQJQRo__1x7O0AR5JhvxaENNUAZiHugqgkqUcAhmIbIr7PRVMA",
    },
    {
        id: "4",
        pic: "/assets/hotels_resorts_f1accbe6-4f03-4289-a1f7-4ff00ff4aa52.jpg",
        country: "Jamaica",
        city: "Montego Bay",
        timeframe: "July 2020",
        description: "Montego Bay, a popular tourist destination in Jamaica, is a tropical paradise known for its stunning beaches, lush landscapes, and vibrant Caribbean culture. Visitors to Montego Bay can relax on the powdery sands of Doctor's Cave Beach, explore the historic Rose Hall Great House, and savor the spicy flavors of Jamaican jerk cuisine. With its warm climate and friendly atmosphere, Montego Bay offers a perfect blend of relaxation and adventure for travelers seeking a tropical escape.",
        google: "https://earth.google.com/web/search/Jamaica/@18.11933375,-77.2761154,226.84434627a,282805.9356268d,35y,0h,0t,0r/data=CnIaSBJCCiUweDhlZGEyYTFiYzZjZjcxOWQ6MHg1OWEwZDFjMGI1MTIwZWZhGVJDG4ANHDJAIRiT_l4KU1PAKgdKYW1haWNhGAIgASImCiQJ6XJbxhmnOEARaG1mThkTMkAZN9Pj7-QQUsAhhF_Vciu3VcA",
    },
    {
        id: "5",
        pic: "/assets/image.jpg",
        country: "Belize",
        city: "Belize City",
        timeframe: "March 2019",
        description: "Belize City, the largest city in Belize, is a coastal hub that offers a gateway to the country's natural wonders and rich cultural heritage. Situated along the Caribbean Sea, it serves as a starting point for exploring the nearby Belize Barrier Reef, one of the world's top diving and snorkeling destinations. In Belize City, visitors can also delve into the country's history by visiting museums, strolling through colorful neighborhoods, and experiencing the vibrant mix of cultures that define this charming Central American city.",
        google: "https://earth.google.com/web/search/Belize/@17.1907804,-88.3201439,3.32816292a,568536.95658526d,35y,0h,0t,0r/data=CnEaRxJBCiUweDhmNWM1YjNlYzExMmZhZjk6MHhmNjRhOGE0ZDNmMWVlMzRlGTlDccebMDFAIa62Yn_ZH1bAKgZCZWxpemUYAiABIiYKJAnpPYvKZOwyQBExujFgz0wxQBkd4HwdP-NSwCHllV2iGMBTwA",
    },
    {
        id: "6",
        pic: "/assets/LICENSE_Chef Tita _Dominican Republic_(c) GettyImages-1068111930_CNT (US)_Andrea Edelman.webp",
        country: "The Dominican Republic",
        city: "Santo Domingo",
        timeframe: "January 2018",
        description: "Santo Domingo, the capital city of the Dominican Republic, is a captivating blend of historical charm and modern vibrancy. It boasts a rich colonial heritage as home to the first European settlement in the Americas, with the historic Zona Colonial offering well-preserved colonial-era architecture and sites like the Alcázar de Colón. Meanwhile, the city's bustling streets, vibrant nightlife, and beautiful coastal areas along the Caribbean Sea make it a dynamic and exciting destination for travelers seeking culture and leisure.",
        google: "https://earth.google.com/web/search/Dominican+Republic/@18.6698995,-70.130055,538.3613667a,563807.30095439d,35y,0h,0t,0r/data=Cn0aUxJNCiUweDhlYWY4ODM4ZGVmMWI2ZjU6MHhhNjAyMGYyNDA2MGRmN2UwGWjlXmBWvDJAIVlqvd9oilHAKhJEb21pbmljYW4gUmVwdWJsaWMYAiABIiYKJAku48wYmM8yQBGHyJo7swUvQBkuDC3cEjRVwCGYNYGd5_RWwA",
    },
    {
        id: "7",
        pic: "/assets/marquee-uk.webp",
        country: "The United Kingdom",
        city: "London",
        timeframe: "November 2017",
        description: "London, the capital of the United Kingdom, is a global metropolis renowned for its rich history, diverse culture, and iconic landmarks. From the historic Tower of London to the modern architecture of the Shard, the city seamlessly blends its past and present. With world-class museums, theaters, shopping districts, and a vast array of international cuisine, London offers an unparalleled urban experience for visitors from around the world.",
        google: "https://earth.google.com/web/search/uk/@54.55127985,-4.4737716,4.92662568a,2761249.88611428d,35y,0h,0t,0r/data=CmwaQhI8CiQweDI1YTNiMTE0MmM3OTFhOToweGM0ZjhhMDQzMzI4ODI1N2EZLJyk-WOwS0AhFoOHad98C8AqAnVrGAIgASImCiQJjo-Q8XdGNEARTKT4iCEAMUAZ0m2irJKnUMAhYmnH9xJpUsA",
    },
    {
        id: "8",
        pic: "/assets/paris-adobestock-327345878.png",
        country: "France",
        city: "Paris",
        timeframe: "March 2016",
        description: "Paris, often referred to as the 'City of Love' and the capital of France, is a timeless and enchanting metropolis that exudes romance, culture, and artistry. It is home to iconic landmarks like the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral, each steeped in history and beauty. Visitors to Paris can savor delectable pastries at charming cafés, stroll along the Seine River, and immerse themselves in the city's artistic heritage, making it an enduring destination for lovers of art, cuisine, and romance.",
        google: "https://earth.google.com/web/search/France/@46.21926495,2.05169995,470.83836161a,1647065.00239236d,35y,0h,0t,0r/data=CnAaRhJACiQweGQ1NGEwMjkzMzc4NTczMToweDZiZmQzZjk2Yzc0N2Q5ZjcZ1qnyPSMdR0Ah8GskCcK1AUAqBkZyYW5jZRgCIAEiJgokCaOU5gLDSk1AEQux6BcCF0VAGRcvzoG5YEBAIR_1RZoC2kTA",
    },
    {
        id: "9",
        pic: "/assets/UltimateMexicoCity__HERO_shutterstock_1058054480.jpg",
        country: "Mexico",
        city: "Mexico City",
        timeframe: "December 2015",
        description: "Mexico City, the vibrant capital of Mexico, is a sprawling megacity that blends ancient traditions with modernity. Its rich history is reflected in archaeological sites like the Templo Mayor and the stunning murals of Diego Rivera at the National Palace. The city's bustling streets are filled with colorful markets, world-class cuisine, and a lively cultural scene, making it a captivating destination for travelers seeking a taste of Mexico's diverse heritage and contemporary flair.",
        google: "https://earth.google.com/web/search/Mexico/@23.5541269,-102.62050005,2071.54620303a,4364316.95579721d,35y,0h,0t,0r/data=CnEaRxJBCiUweDg0MDQzYTNiODg2ODUzNTM6MHhlZDY0YjRiZTZiMDk5ODExGYBHVKhuojdAISFwJNBgo1nAKgZNZXhpY28YAiABIiYKJAnH0naMhxxJQBFCy81l_ylEQBkU7Qn28gwyQCHV0UkX9eQrwA",
    },
]